# Ref: https://fluxcd.io/flux/installation/configuration/vertical-scaling/#increase-the-number-of-workers-and-limits
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            tolerations:
            - effect: NoSchedule
              key: karpenter.sh/controller
              operator: Exists
            - key: CriticalAddonsOnly
              operator: Exists

    target:
      kind: Deployment
      name: "(kustomize-controller|helm-controller|source-controller|image-automation-controller|image-reflector-controller|notification-controller)"