name: Bandit Python Security Scan

on:
  push:
  #pull_request:
  #  branches:
 #     - '*'
  #schedule:
  #  - cron: '0 0 * * 1'
  #watch:
  #  types: [started]
    
jobs:
  python-scan:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - {python-version: '3.13' }
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python Modules
        run: |
          python -m pip install --upgrade pip
          pip install -U bandit pip-audit setuptools .
      - name: Bandit Scan
        run: |
          bandit -r .
      - name: Pip Audit
        run: |
          # GHSA-wfm5-v35h-vwf4  gitpython is a dependency of pip-audit not cid-cmd
          # GHSA-cwvm-v4w8-q58c  gitpython is a dependency of pip-audit not cid-cmd
          pip-audit --ignore-vuln GHSA-wfm5-v35h-vwf4 --ignore-vuln GHSA-cwvm-v4w8-q58c

  python-pylint-cid:
    runs-on: ubuntu-24.04
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install pylint
        run: |
          pip install pylint
      - name: PyLint
        run: |
          pylint ./src/