name: Continuous Delivery

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch all history.
          fetch-depth: 0
          persist-credentials: false
      - env:
          GITHUB_TOKEN: ${{ secrets.DOTTBOTT_TOKEN }}
        name: Release
        uses: ridedott/release-me-action@master
        #with:
        #  release-rules: |
        #    [
        #      { "release": "patch", "type": "build" },
        #      { "release": "patch", "type": "chore" },
        #      { "release": "patch", "type": "ci" },
        #      { "release": "patch", "type": "improvement" },
        #      { "release": "patch", "type": "refactor" },
        #    ]
        with:
          disable-changelog: true
