name: Continuous Delivery

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch all history.
          fetch-depth: 0
          persist-credentials: false
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Release
        uses: ridedott/release-me-action@master
        with:
          commit-assets: |
            ./src
          dry-run: true
          disable-changelog: true
          release-branches: '["main"]'
